// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9Iz04yrpfSA2djYNpLU2VHwZzDT8pEQ',
    appId: '1:880295983945:web:4211380a5366396a3db898',
    messagingSenderId: '880295983945',
    projectId: 'fruit-hub-2d23f',
    authDomain: 'fruit-hub-2d23f.firebaseapp.com',
    storageBucket: 'fruit-hub-2d23f.firebasestorage.app',
    measurementId: 'G-B4T8FQSJ3X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNTk8xTeN0CN_gUJungKZIt5aOG9lSqJU',
    appId: '1:880295983945:ios:a9540e7d74587dea3db898',
    messagingSenderId: '880295983945',
    projectId: 'fruit-hub-2d23f',
    storageBucket: 'fruit-hub-2d23f.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNTk8xTeN0CN_gUJungKZIt5aOG9lSqJU',
    appId: '1:880295983945:ios:a9540e7d74587dea3db898',
    messagingSenderId: '880295983945',
    projectId: 'fruit-hub-2d23f',
    storageBucket: 'fruit-hub-2d23f.firebasestorage.app',
    iosBundleId: 'com.example.fruithub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH9Iz04yrpfSA2djYNpLU2VHwZzDT8pEQ',
    appId: '1:880295983945:web:da0e87ac42fd09c33db898',
    messagingSenderId: '880295983945',
    projectId: 'fruit-hub-2d23f',
    authDomain: 'fruit-hub-2d23f.firebaseapp.com',
    storageBucket: 'fruit-hub-2d23f.firebasestorage.app',
    measurementId: 'G-J1NCLV4NFJ',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzNF9LsurKf1O8-esosQ5ngsStflmfOQ',
    appId: '1:880295983945:android:3008828bb706ee8e3db898',
    messagingSenderId: '880295983945',
    projectId: 'fruit-hub-2d23f',
    storageBucket: 'fruit-hub-2d23f.firebasestorage.app',
  );
}
